services:
  - type: web
    name: movie-downloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium --with-deps
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /home/render/.cache/ms-playwright
      - key: PYTHONPATH
        value: .
      - key: PYTHON_VERSION
        value: 3.9.13
    disk:
      name: movie-data
      mountPath: /opt/render/project/src/downloads
      sizeGB: 10